### ISSUE TITLE
Folders with spaces

### ISSUE THREAD

**Issue by tvaughan73** [Syren7/owncloudApiBundle#1]
I am having an issue creating directories where the name has a space.  Is the name supposed to be formatted in any special way? For example if I try to create the directory tomtest it works OK.  If I try to create the directory tom test it does not work.

Thanks!
Tom

**Comment by TuemmlerKon** [comment]
Hi Tom,

which version of OC do you use? Foldernames with spaces should normally work but I can't say since which version of OC... I've tested it with 8.2.2

Could you possibly post your code for creating that directory?

Konstantin

Edit: Do you use the "owncloud_folder:" parameter or is it empty?

**Comment by tvaughan73** [comment]
Sorry for the very late reply.  I didn't get a notification from github.  I recently upgraded OC to 9.1.0.15 and decided to revisit the issue I was having and see if it worked now.  Unfortunately, I am still having the problem.  

This works:

```
$oc = new Syren7\OwncloudApiBundle\Service\OwncloudFilesystem('https://myowncloud', 'myuser', 'userpass', '');
$oc->createDirectory('SomeDir');
```

This will not work:

```
$oc = new Syren7\OwncloudApiBundle\Service\OwncloudFilesystem('https://myowncloud', 'myuser', 'userpass', '');
$oc->createDirectory('Some Dir');
```

Server is using PHP 5.6.24 if that matters.

**Comment by tvaughan73** [comment]
Never mind on this.  Finally figured out it was mod_security causing the issue.  GRRRR.
